spring:
  profiles:
    group:
      dev:
        - db
        - security
      test:
        - test
        - security
  jackson:
    serialization:
      fail-on-empty-beans: false
        - file
        - mail
server:
  port: 8082
logging:
  level:
    sql: debug