spring:
  profiles:
    group:
      prod:
        - db
        - security
        - file
        - mail
      dev:
        - db
        - security
        - file
        - mail

server:
  port: 8082
logging:
  level:
    sql: debug
