spring:
  profiles:
    group:
      prod:
        - db
        - security
<<<<<<< HEAD
        - file
        - mail
      test:
        - test
        - security
        - file
        - mail
  jackson:
    serialization:
      fail-on-empty-beans: false
=======
        - mail
        - file
      dev:
        - devdb
        - security
        - mail
        - file
>>>>>>> main
server:
  port: 8082
logging:
  level:
    sql: debug