spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ON_SECRET
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ON_SECRET
            client-secret: ON_SECRET
            scope:
              - email
              - profile
          github:
            client-id: ON_SECRET
            client-secret: ON_SECRET
            scope: read:user, user:email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  profiles:
    group:
      dev:
        - db
        - security
        - file
        - mail
server:
  port: 8082
logging:
  level:
    sql: debug