spring:
  profiles:
    group:
      prod:
        - db
        - security
        - mail
        - file
      dev:
        - devdb
        - security
        - mail
        - file
server:
  port: 8082
logging:
  level:
    sql: debug