spring:
  profiles:
    group:
      prod:
        - db
        - security
        - file
        - mail
      dev:
        - db
        - security
        - file
        - m
      test:
        - test
        - security
        - file
        - mail
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8082
logging:
  level:
    sql: debug