spring:
  profiles:
    group:
      dev:
        - db
        - security
<<<<<<< HEAD
      test:
        - test
        - security
=======
  jackson:
    serialization:
      fail-on-empty-beans: false
>>>>>>> heeyeong
server:
  port: 8082
logging:
  level:
    sql: debug